config/routes.rb
Rails.application.routes.draw do

  resources :rates
  resources :users
  root to: "users#book"
  get '/' => 'users#book'
  get '/login' => 'users#login'
  post '/login' => 'users#login'
  get '/logout' => 'users#logout'
  get '/book' => 'users#book' 
  post '/book' => 'users#book'
  get '/book/:id' => 'users#bookticket'
  get '/cancel/:id' => 'users#cancel' ,as: :book_return
  get '/mytickets' => 'users#mytickets'
  get '/contact' => 'users#contact'

  get 'signup' => 'users#new'

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  has_many :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
belongs_to :rate
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_filter :authorize

  $LOCATION = ["Chennai", "Mumbai", "New Delhi"]
  def authorize
      username = cookies[:username]
      if !username.present? and params["action"] != "new" and params["action"] != "create"
        redirect_to "/login" and return if params["action"] != "login" 
      elsif params["action"] == "login"
        page = "/book"
          redirect_to page and return
      end
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: 'Rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:location1, :location2, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :user, except: [:login, :logout, :new, :create]

  def book
    if params["location1"].present? and params["location2"].present?
      if  params["location1"] ==  params["location2"]
        @notice = "origin and destination cannot be same" 
      else
        @rate = Rate.find_by(:location1 => params["location1"], location2: params[:location2])
      end
    end
  end

  def bookticket
    id = params[:id]
    t = Ticket.create({:rate_id => id, :user_id => @user.id})
    redirect_to "/mytickets"
    @booked = true
  end

  def mytickets
    @mytickets = Ticket.joins(:rate).where(:user_id => @user.id)
    render layout: false
  end

  def cancel
    book_id = params[:id]
    u = Ticket.find_by({:id => book_id, :user_id => @user.id})
    u.delete if u.present?
    @cancel = true
    redirect_to "/mytickets"
  end

  def contact
    render layout: false
  end

  def login
    if params["username"].present? and params["password"].present?
      user = User.find_by(username: params["username"], password: params["password"])
      if user.present?
        cookies["username"] = user.username
        page = "/book"
        redirect_to page and return
      end
      @invalid = true
    end
    render layout: "login"
  end

  def logout
    cookies.delete(:username)
    cookies.delete(:is_admin)
    redirect_to "/" and return
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    render layout: "login"
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to "/login", notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end

    def user
      @user = User.find_by(username: cookies["username"])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bus Ticket System</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li class="<%= controller.class == UsersController and controller.action_name == 'book' ? 'active' : '' %>"><a href="/book">Book Ticket</a></li>
        <li class="<%= controller.class == UsersController and controller.action_name == 'mytickets' ? 'active' : '' %>"><a href="/mytickets">MY Tickets</a></li>
        <li><a href="/contact">CONTACT US</a></li>
        <li><a href="/logout">LOGOUT</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
<div class="row">
<div class="col-md-10 col-md-offset-1">
<%= yield %>
  
</div>
</div>
</div>

</body>
</html>

app/views/layouts/login.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Bus Ticket System</a>

    </div>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/rates/_form.html.erb
<%= form_for @rate, :html => { :class => "form-horizontal rate" } do |f| %>

  <% if @rate.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@rate.errors.count, "error") %> prohibited this rate from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @rate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :location1, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location1, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location1) %>
  </div>
  <div class="form-group">
    <%= f.label :location2, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location2, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location2) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rates_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/rates/edit.html.erb
<%- model_class = Rate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rates/index.html.erb
<%- model_class = Rate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:location1) %></th>
      <th><%= model_class.human_attribute_name(:location2) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rates.each do |rate| %>
      <tr>
        <td><%= link_to rate.id, rate_path(rate) %></td>
        <td><%= rate.location1 %></td>
        <td><%= rate.location2 %></td>
        <td><%= rate.price %></td>
        <td><%=l rate.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      rate_path(rate), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rate_path(rate), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rate_path(rate),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rate_path,
            :class => 'btn btn-primary' %>

app/views/rates/new.html.erb
<%- model_class = Rate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rates/show.html.erb
<%- model_class = Rate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:location1) %>:</strong></dt>
  <dd><%= @rate.location1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location2) %>:</strong></dt>
  <dd><%= @rate.location2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @rate.price %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              rates_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rate_path(@rate), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              rate_path(@rate),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/users/_form.html.erb
          <%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>
          <% if @user.errors.any? %>
            <div id="error_expl" class="panel panel-danger">
              <div class="panel-heading">
                <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
              </div>
              <div class="panel-body">
                <ul>
                <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            </div>
          <% end %>

  <div class="form-group ">
    <%= f.label "username", :class => 'control-label col-lg-3' %>
    <div class="col-lg-9">
      <%= f.text_field "username", :class => 'form-control' %>
    </div>
    <%=f.error_span(:username) %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-3' %>
    <div class="col-lg-9">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Create Account", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>
    <% end %>

app/views/users/book.erb
<div class="page-header">
  <h1>Find Busses</h1>
</div>
<div class="alert alert-danger alert-dismissible fade in notice-alert" style="<%= 'display:none' unless @notice.present? %> "role="alert"><button type="button" class="close" onclick="$(this).closest('.alert').hide()"><span aria-hidden="true">×</span></button> 
  <span id="alert-message">
    <%= @notice %>
  </span>
</div>
<form action="book" method="post">
  
<div class="row">
<div class="col-md-5">
  <label for="exampleInputEmail1">Origin</label>

  <select class="form-control" name="location1" required>
  <option value="" disabled selected="selected" >Select Origin</option>
  <% $LOCATION.each do |l| %>
    <option value="<%= l %>"> <%= l %></option>
  <% end %>
  </select>
</div>
<div class="col-md-5">
  <label for="exampleInputEmail1">Destination</label>
  <select class="form-control" value="" name="location2" required>
  <option value="" disabled selected="selected">Select Destination</option>
  <% $LOCATION.each do |l| %>
    <option value="<%= l %>"> <%= l %></option>
  <% end %>
    </select>
</div>
</div>
<br>
<button type="submit" class="btn btn-primary">Search</button>
</form>
  <% if @rate.present? %>
  <br>
  <h4>Result</h4>
  <div class="row">
  <div class="col-md-3">
  <label for="exampleInputEmail1">Origin</label><br>
  <%= @rate.location1 %>
</div>
  <div class="col-md-3">
  <label for="exampleInputEmail1">Destination</label><br>
  <%= @rate.location2 %>
</div>
  <div class="col-md-3">
    <label for="exampleInputEmail1">Price</label><br>
    <%= @rate.price %>
  </div>
  <div class="col-md-3">
  <a href="book/<%= @rate.id %>"><button class="btn  btn-success">Book</button></a>
  </div>
</div>
  <% end %>

  <% if @booked %>

<script type="text/javascript">
alert("book lented")
</script>

  <% end %>

app/views/users/contact.erb
<%= 
(`python lib/contact.py`).html_safe %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/login.erb
<div class="container">

        <p><br/></p>
        <div class="row">
    
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                            <div class="page-header text-center">
                            <h3>Login</h3>
                        </div>
                        <div class="alert alert-danger alert-dismissible fade in notice-alert" style="<%= 'display:none' unless @invalid.present? %>"role="alert"> Invalid Username/password<button type="button" class="close" onclick="$(this).closest('.alert').hide()"><span aria-hidden="true">×</span></button> 
                          <span id="alert-message">
                            <%= @notice %>
                          </span>
                        </div>

                        <div class="alert alert-success alert-dismissible fade in notice-alert" style="<%= 'display:none' unless notice.present? %> "role="alert"><button type="button" class="close" onclick="$(this).closest('.alert').hide()"><span aria-hidden="true">×</span></button> 
                          <span id="alert-message">
                            <%= notice %>
                          </span>
                        </div>
                        <form role="form" action="./login" method="post">
                            <div class="form-group">
                                    <label for="exampleInputEmail1">USERNAME</label>
                                    <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                    <input type="text" class="form-control LoNotSensitive" name="username" required placeholder="Enter email">
                                </div>
                            </div>
                            <input type="hidden" name="redirect_to" value="<%= @redirect_to %>"></input>
                            <div class="form-group">
                                    <label for="exampleInputPassword1">PASSWORD</label>
                                    <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-star"></span></span>
                                    <input type="password" class="form-control" name="password" required placeholder="Password">
                                </div>
                            </div>
                            <hr/>
                            <button id="loginButton" type="submit" class="btn btn-primary "><span class="glyphicon glyphicon-lock"></span> Login</button>
                            <a href="/signup"><button id="loginButton" type="button"  class="btn btn-primary "><span class="glyphicon glyphicon-lock"></span> Signup</button></a>
                            <p><br/></p>
                        </form>
                        <div class="modal fade bs-example-modal-sm" id="myPleaseWait" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">
                                            <span class="glyphicon glyphicon-time">
                                            </span>Please Wait
                                        </h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-info
                                            progress-bar-striped active" style="width: 100%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/mytickets.erb
<%= 
(`php lib/mytickets.php #{@user.id}`).html_safe %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
        <div class="panel-body">
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>
</div>
</div>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>